import=[
	"~/.config/alacritty/catppuccin-frappe.toml"
]

[font]
size=20

[font.normal]
family = "MesloLGS Nerd Font Mono"

[env]
TERM = "xterm-256color"

[window]
decorations = "none"

[window.padding]
y = 0

