import=[
	"~/.config/alacritty/catppuccin-frappe.toml"
]

[font]
size=20

[font.normal]
family = "UbuntuMono Nerd Font"

[env]
TERM = "xterm-256color"

[window]
decorations = "none"

[window.padding]
x = 5 
y = 0

